name: Validate
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Lint
        run: swiftformat --lint .
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Xcode Select
        run: sudo xcode-select --switch /Applications/Xcode_15.1.app
      - name: Fetch Dependencies
        run: tuist install
      - name: Run ScoreFive Tests
        run: tuist test ScoreFive
      - name: Run FiveKit Tests
        run: tuist test FiveKit
